---
roles:
  pe-puppet-master:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
      linked_clone: true
      cpus: 4
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 8192]
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap, role: !ruby/sym master}

  pe-puppet-agent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provider:
      type: virtualbox
      linked_clone: true
      cpus: 2
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
